export const ICON_GLYPHS = {
  flash: '\ued3c',
  flashAuto: '\ued3d',
  watermark: '\uec69',
  cameraFlip: '\ueb34',
  album: '\uee4a',
  customWatermark: '\uec7f',
  undo: '\uea58',
  redo: '\uea5a',
  save: '\uefb2',
  close: '\ueb98',
  check: '\ueb7a',
  download: '\uec53',
  rotateLeft: '\uea39',
  rotateRight: '\ueb92',
  crop: '\uec01',
  draw: '\ueb00',
  sticker: '\uf37e',
  text: '\uf201',
  add: '\uea12',
}
