/**
 * 贴纸分类数据
 * type: 'emoji' — 纯字符表情 | 'image' — 外部图片贴纸
 */
export const STICKER_CATEGORIES = [
  {
    key: 'emoji',
    label: '表情',
    icon: '😊',
    type: 'emoji',
    items: [
      { name: '笑脸', emoji: '😊' },
      { name: '大笑', emoji: '😂' },
      { name: '可爱', emoji: '🥰' },
      { name: '飞吻', emoji: '😘' },
      { name: '酷', emoji: '😎' },
      { name: '思考', emoji: '🤔' },
      { name: '拥抱', emoji: '🤗' },
      { name: '可怜', emoji: '🥺' },
      { name: '生气', emoji: '😤' },
      { name: '惊恐', emoji: '😱' },
      { name: '哭泣', emoji: '😭' },
      { name: '吐舌', emoji: '😜' },
      { name: '晕', emoji: '😵' },
      { name: '瞌睡', emoji: '😴' },
      { name: '恶心', emoji: '🤢' },
      { name: '魔鬼', emoji: '😈' },
      { name: '骷髅', emoji: '💀' },
      { name: '外星人', emoji: '👽' },
      { name: '小丑', emoji: '🤡' },
      { name: '便便', emoji: '💩' },
    ],
  },
  {
    key: 'gesture',
    label: '手势',
    icon: '👆',
    type: 'emoji',
    items: [
      { name: '点赞', emoji: '👍' },
      { name: '踩', emoji: '👎' },
      { name: '胜利', emoji: '✌️' },
      { name: '握手', emoji: '🤝' },
      { name: '祈祷', emoji: '🙏' },
      { name: '肌肉', emoji: '💪' },
      { name: '打call', emoji: '🤙' },
      { name: '指上', emoji: '👆' },
      { name: '指下', emoji: '👇' },
      { name: '向左', emoji: '👈' },
      { name: '向右', emoji: '👉' },
      { name: 'OK', emoji: '👌' },
      { name: '拳头', emoji: '👊' },
      { name: '举手', emoji: '🖐️' },
      { name: '比心', emoji: '🫶' },
      { name: '鼓掌', emoji: '👏' },
      { name: '摇滚', emoji: '🤘' },
      { name: '合十', emoji: '🤲' },
      { name: '写信', emoji: '✍️' },
      { name: '摇滚2', emoji: '🫰' },
    ],
  },
  {
    key: 'nature',
    label: '自然',
    icon: '🌈',
    type: 'emoji',
    items: [
      { name: '星星', emoji: '⭐' },
      { name: '月亮', emoji: '🌙' },
      { name: '太阳', emoji: '☀️' },
      { name: '彩虹', emoji: '🌈' },
      { name: '火焰', emoji: '🔥' },
      { name: '闪电', emoji: '⚡' },
      { name: '钻石', emoji: '💎' },
      { name: '花朵', emoji: '🌸' },
      { name: '玫瑰', emoji: '🌹' },
      { name: '花束', emoji: '💐' },
      { name: '四叶草', emoji: '🍀' },
      { name: '雪花', emoji: '❄️' },
      { name: '水滴', emoji: '💧' },
      { name: '海浪', emoji: '🌊' },
      { name: '风', emoji: '🌬️' },
      { name: '火山', emoji: '🌋' },
      { name: '流星', emoji: '🌠' },
      { name: '太阳2', emoji: '🌞' },
      { name: '满月', emoji: '🌕' },
      { name: '白云', emoji: '☁️' },
    ],
  },
  {
    key: 'tag',
    label: '标签',
    icon: '🏷️',
    type: 'emoji',
    items: [
      { name: '勾选', emoji: '✅' },
      { name: '叉号', emoji: '❌' },
      { name: '满分', emoji: '💯' },
      { name: '庆祝', emoji: '🎉' },
      { name: '皇冠', emoji: '👑' },
      { name: '奖章', emoji: '🏅' },
      { name: '气泡', emoji: '💬' },
      { name: '闪光', emoji: '✨' },
      { name: '爱心', emoji: '❤️' },
      { name: '叹号', emoji: '❗' },
      { name: '问号', emoji: '❓' },
      { name: '禁止', emoji: '🚫' },
      { name: '奖杯', emoji: '🏆' },
      { name: '礼物', emoji: '🎁' },
      { name: '气球', emoji: '🎈' },
      { name: '目标', emoji: '🎯' },
      { name: '钥匙', emoji: '🔑' },
      { name: '铃铛', emoji: '🔔' },
      { name: '锁', emoji: '🔒' },
      { name: '火箭', emoji: '🚀' },
    ],
  },
  {
    key: 'decoration',
    label: '装饰',
    icon: '🎀',
    type: 'image',
    items: [],
  },
]
